### ISSUE TITLE
Password expire after root password reset

### ISSUE THREAD

**Issue by cloudnull** [alunduil/singularity#3]
A nice to have would be a feature that expires the root password after a password reset has been performed via the agent.  This expire could be immediate or after x amount of days.

**Comment by alunduil** [comment]
Since the user can pick their password in openstack do we want this feature?  If I'm setting the password to what I desire why would I ever want to reset it on the next login?  This sounds like something that the security policy of the user's system should take care of.  Let me know what you think and if you think this is still something useful.
